/** Official windows and crawl lists. Shared by the H5 and the daily refresh script. */

export const KEYWORDS = [
  "林下经济",
  "林下种植",
  "生态修复",
  "矿山",
  "申报",
  "奖补",
  "EOD",
  "光伏",
  "农林",
  "储备林",
  "山水林田湖草",
  "全域土地",
  "重点生态保护修复",
  "绿色矿山",
  "林药",
  "小品种",
  "哀牢山",
  "金沙江",
];

export const applyWindows = [
  {
    id: "w-mof-mine",
    title: "中央历史遗留矿山生态修复示范工程",
    via: "企业不直接报财政部。市县入库 → 省厅排序 → 部里竞争性评审。",
    url: "http://bgt.mof.gov.cn/zhuantilanmu/rdwyh/czyw/202502/t20250220_3958748.htm",
    portal: "http://zyhj.mof.gov.cn/zxzyzf/zdstbhxf/",
    region: "全国",
    status: "rolling",
    window: "随年度通知",
    topics: ["mine", "fund"],
  },
  {
    id: "w-mof-fund",
    title: "重点生态保护修复治理资金（山水 + 矿山）",
    via: "中央对省转移支付。看下达/提前下达预算通知，再找本省实施方案。",
    url: "http://zyhj.mof.gov.cn/zxzyzf/zdstbhxf/",
    portal: "http://m.mof.gov.cn/zcfb/202601/t20260114_3981840.htm",
    region: "全国",
    status: "open",
    window: "预算下达后由省分解",
    topics: ["landscape", "fund"],
  },
  {
    id: "w-yn-reserve",
    title: "云南国家储备林：州（市）组卷，省林草局审查后报国家林草局备案",
    via: "建设主体须是法人企事业单位、村集体或林业合作社。入库后才能申请中央资金和金融贷款。配套林下经济可列项目资金，但不超过50%。",
    url: "https://www.yn.gov.cn:8443/zwgk/zfgb/2025/2025d18q/szbmgfxwj/202509/t20250928_318278.html",
    portal: "https://lcj.yn.gov.cn/",
    region: "云南",
    status: "open",
    window: "按州（市）批次申报入库",
    topics: ["understory", "fund"],
  },
  {
    id: "w-yn-green-mine",
    title: "云南绿色矿山：企业在省绿色矿山管理信息系统网上申请",
    via: "县初审 → 州复审 → 企业自评 → 省级委托第三方现场评估 → 公示进名录。国家级从省级名录择优推荐。",
    url: "https://dnr.yn.gov.cn/html/2025/tongzhigonggao_0422/4049423.html",
    portal: "https://dnr.yn.gov.cn/",
    region: "云南",
    status: "open",
    window: "完成建设任务后随时申报",
    topics: ["mine"],
  },
  {
    id: "w-yn-mine-pack",
    title: "云南历史遗留矿山修复：进省储备库，由省厅对上中央示范",
    via: "市县先按《云南省历史遗留矿山生态修复项目管理办法》入库。企业不直接报财政部。保山、大理、红河和图斑连片区优先。",
    url: "https://dnr.yn.gov.cn/html/2026/shengtingdongtai_0116/4051833.html",
    portal: "https://dnr.yn.gov.cn/",
    region: "云南",
    status: "rolling",
    window: "十五五滚动，有条件州（市）清零",
    topics: ["mine", "fund"],
  },
  {
    id: "w-yn-under",
    title: "云南林下经济：省里没有专项奖补口，交叉资金和储备林才是入口",
    via: "林下开发无专门审批。抚育采伐办采伐证。钱走设施农业奖补/贴息、中小企业专项、储备林配套产业，以及松茸贷、草果贷、天麻贷。盯行动方案正式印发。",
    url: "https://lcj.yn.gov.cn/html/2026/gongshigonggao_0622/76863.html",
    portal: "https://lcj.yn.gov.cn/html/gongshigonggao/",
    region: "云南",
    status: "open",
    window: "行动方案征求意见已结束，等正式稿",
    topics: ["understory"],
  },
  {
    id: "w-gx-reserve",
    title: "广西国土空间生态修复项目入库 / 直补奖补",
    via: "市县向自治区储备库申报。未入库不能直补。",
    url: "https://dnr.gxzf.gov.cn/zfxxgk/fdzdgknr/zcfg/gfxwj/t18559089.shtml",
    portal: "https://dnr.gxzf.gov.cn/",
    region: "广西",
    status: "open",
    window: "十五五滚动",
    topics: ["mine", "landscape"],
  },
  {
    id: "w-fj-under",
    title: "福建林下经济 / 储备林带林下空间",
    via: "县林业主管部门组织经营主体申报省级专项；储备林实施主体把林下写入合同。",
    url: "https://lyj.fujian.gov.cn/zwgk/zcfg/gfxwjnew/202602/t20260224_7099933.htm",
    portal: "https://lyj.fujian.gov.cn/zwgk/zcfg/gfxwjnew/",
    region: "福建",
    status: "open",
    window: "随省级专项批次",
    topics: ["understory"],
  },
  {
    id: "w-nx-jy",
    title: "泾源县林下经济产业补助",
    via: "乡镇初审公示 → 县林草局审核核查。事后奖补。",
    url: "https://www.nxjy.gov.cn/xwzx/gsgg/202603/t20260319_5198025.html",
    portal: "https://www.nxjy.gov.cn/xwzx/gsgg/",
    region: "宁夏",
    status: "closed",
    window: "2026-03-17 至 2026-04-30，备明年",
    topics: ["understory"],
  },
  {
    id: "w-nx-dwk",
    title: "大武口区林下经济产业补助",
    via: "区自然资源局受理，事后奖补。",
    url: "https://www.dwk.gov.cn/xxgk/zfxxgkml/jjjs/ylnm_45991/202603/t20260317_5195864.html",
    portal: "https://www.dwk.gov.cn/",
    region: "宁夏",
    status: "closed",
    window: "2026-03-17 至 2026-04-17，备明年",
    topics: ["understory"],
  },
  {
    id: "w-nh",
    title: "宁化县省级财政林下经济专项",
    via: "县林业局遴选经营主体。",
    url: "http://www.fjnh.gov.cn/xxgk/gggs/202502/t20250217_2100699.htm",
    portal: "http://www.fjnh.gov.cn/xxgk/gggs/",
    region: "福建",
    status: "closed",
    window: "2025年窗口已过，盯2026/2027专项",
    topics: ["understory"],
  },
  {
    id: "w-forest-base",
    title: "国家林下经济示范基地认定",
    via: "经营主体报县林草局，逐级到国家林草局。下一批次以局通知为准。",
    url: "http://www.forestry.gov.cn/lyj/1/gkgfxwj/20231225/539915.html",
    portal: "https://www.forestry.gov.cn/c/www/gsgg_4.jhtml",
    region: "全国",
    status: "rolling",
    window: "随认定通知",
    topics: ["understory"],
  },
];

export const crawlSources = [
  {
    id: "mof-repair-fund",
    name: "财政部 · 重点生态保护修复治理资金",
    url: "http://zyhj.mof.gov.cn/zxzyzf/zdstbhxf/",
    region: "全国",
    topics: ["fund", "mine", "landscape"],
    active: true,
  },
  {
    id: "mof-notice",
    name: "财政部 · 政策发布",
    url: "http://m.mof.gov.cn/zcfb/",
    region: "全国",
    topics: ["fund"],
    active: true,
  },
  {
    id: "fj-lyj",
    name: "福建省林业局 · 部门文件",
    url: "https://lyj.fujian.gov.cn/zwgk/zcfg/gfxwjnew/",
    region: "福建",
    topics: ["understory"],
    active: true,
  },
  {
    id: "gx-dnr",
    name: "广西自然资源厅 · 规范性文件",
    url: "https://dnr.gxzf.gov.cn/zfxxgk/fdzdgknr/zcfg/gfxwj/",
    region: "广西",
    topics: ["mine", "landscape"],
    active: true,
  },
  {
    id: "dt-gov",
    name: "大同市政府办文件",
    url: "https://www.dt.gov.cn/dtszf/tzbf/",
    region: "山西",
    topics: ["understory"],
    active: false,
  },
  {
    id: "nx-jy",
    name: "泾源县公示公告",
    url: "https://www.nxjy.gov.cn/xwzx/gsgg/",
    region: "宁夏",
    topics: ["understory"],
    active: true,
  },
  {
    id: "mee-tzgg",
    name: "生态环境部 · 通知公告（EOD）",
    url: "https://www.mee.gov.cn/ywdt/tzgg/",
    region: "全国",
    topics: ["eod"],
    active: true,
  },
  {
    id: "forestry-gsgg",
    name: "国家林草局 · 公示公告",
    url: "https://www.forestry.gov.cn/c/www/gsgg_4.jhtml",
    region: "全国",
    topics: ["understory"],
    active: true,
  },
  {
    id: "yn-lcj-gsgg",
    name: "云南省林草局 · 公示公告",
    url: "https://lcj.yn.gov.cn/html/gongshigonggao/",
    region: "云南",
    topics: ["understory"],
    active: true,
  },
  {
    id: "yn-dnr",
    name: "云南省自然资源厅 · 门户",
    url: "https://dnr.yn.gov.cn/",
    region: "云南",
    topics: ["mine", "landscape"],
    active: true,
  },
];

export const expandSources = [
  {
    name: "大同市政府办文件",
    why: "列表页目前返回 403，先手工打开原文，等反爬放开再进每日抓取。",
    url: "https://www.dt.gov.cn/dtszf/tzbf/",
  },
  {
    name: "自然资源部门户 通知公告",
    why: "十五五矿山图斑销号、国土空间生态修复工程以部里通知为准。",
    url: "https://www.mnr.gov.cn/",
  },
  {
    name: "各省林草局（浙赣黔川湘等）",
    why: "林下奖补窗口几乎都在县/省林草局。云南源已接入，按实际作业县再往下加。",
  },
  {
    name: "云南省公共资源交易平台",
    why: "矿山修复、储备林、绿色矿山相关施工和监理招标的进场口。",
    url: "https://www.ynggzy.com/",
  },
  {
    name: "中国政府采购网 / 各省公共资源交易中心",
    why: "修复施工、EPC 真实进场口，不是政策口。",
    url: "https://www.ccgp.gov.cn/",
  },
  {
    name: "全国公共资源交易平台",
    why: "矿山修复、全域整治招标与资格预审。",
    url: "http://www.ggzy.gov.cn/",
  },
  {
    name: "国家发改委 重大工程 / 特许经营",
    why: "EOD、储备林、农光互补立项口径。",
    url: "https://www.ndrc.gov.cn/",
  },
  {
    name: "国家能源局 复合光伏",
    why: "农光/林光项目核准与并网，对接 NB/T 11897-2025。",
  },
  {
    name: "农业农村部 林下中药材 / 农林复合",
    why: "中药材基地、复合经营与林草部门交叉。",
  },
  {
    name: "国务院客户端 / 各省政务服务网",
    why: "部分奖补已网上办事，可做到‘打开即填’。",
  },
];

export const policyUrls = {
  "p-mine-2025":
    "http://bgt.mof.gov.cn/zhuantilanmu/rdwyh/czyw/202502/t20250220_3958748.htm",
  "p-fund-2026": "http://m.mof.gov.cn/zcfb/202601/t20260114_3981840.htm",
  "p-fund-budget": "http://zyhj.mof.gov.cn/zxzyzf/zdstbhxf/202511/t20251118_3976614.htm",
  "p-fund-issued-2026":
    "http://zyhj.mof.gov.cn/zxzyzf/zdstbhxf/202606/t20260626_3992352.htm",
  "p-gx-15":
    "https://dnr.gxzf.gov.cn/zfxxgk/fdzdgknr/zcfg/gfxwj/t18559089.shtml",
  "p-nx-2026": "https://www.nxjy.gov.cn/xwzx/gsgg/202603/t20260319_5198025.html",
  "p-fj-2026":
    "https://lyj.fujian.gov.cn/zwgk/zcfg/gfxwjnew/202602/t20260224_7099933.htm",
  "p-dt-2026":
    "https://www.dt.gov.cn/dtszf/tzbf/202602/3061cbb217594a4d81a830cead2e1b56.shtml",
  "p-pv-spec":
    "https://ndls.cnis.ac.cn/standard/detail/96d1c26cb2fda9045c32c01f779727dc",
  "p-eod": "https://www.mee.gov.cn/ywdt/tzgg/",
  "p-mineral-law": "https://www.gov.cn/yaowen/liebiao/202411/content_6987759.htm",
  "p-master": "https://www.ndrc.gov.cn/",
  "p-forest-base": "http://www.forestry.gov.cn/lyj/1/gkgfxwj/20231225/539915.html",
  "p-yn-action": "https://lcj.yn.gov.cn/html/2026/gongshigonggao_0622/76863.html",
  "p-yn-qa": "https://lcj.yn.gov.cn/html/2026/liuyanhuifu_0714/77029.html",
  "p-yn-species": "https://lcj.yn.gov.cn/html/2026/gongshigonggao_0113/75956.html",
  "p-yn-reserve":
    "https://www.yn.gov.cn:8443/zwgk/zfgb/2025/2025d18q/szbmgfxwj/202509/t20250928_318278.html",
  "p-yn-green-mine": "https://dnr.yn.gov.cn/html/2025/tongzhigonggao_0422/4049423.html",
  "p-yn-mine-15": "https://dnr.yn.gov.cn/html/2026/shengtingdongtai_0116/4051833.html",
  "p-yn-fund": "https://lcj.yn.gov.cn/html/2025/jianyitianbanli_0610/74779.html",
};
